"""Raspberry Pi Zero 2 W 2x20 socket (PPPC202LFBN-RC).

Package geometry follows the reviewed production definition for PI_ZERO_HEADER.
Electrical simulation is unavailable unless a model is explicitly declared.
"""

from pcb.harness import (
    BoardComponent,
    BoardRegistry,
    ComponentDefinition,
    Courtyard,
    LandPattern,
    Net,
    NoConnect,
    Pad,
    PadKind,
    PadShape,
    Placement,
    Point,
    Product,
)
from shared.components import PI_ZERO_HEADER
from shared.dimensions.case import PI_HEADER_BODY_MM
from shared.electronics.raspberry_pi_header import RaspberryPiHeaderPin

PI_ZERO_HEADER_DEFINITION = ComponentDefinition(
    product=Product(
        key=PI_ZERO_HEADER.key,
        manufacturer=PI_ZERO_HEADER.manufacturer,
        part_number=PI_ZERO_HEADER.mpn,
        package=PI_ZERO_HEADER.package,
        body_mm=(PI_HEADER_BODY_MM[1], PI_HEADER_BODY_MM[0], PI_HEADER_BODY_MM[2]),
        datasheet=PI_ZERO_HEADER.datasheet,
    ),
    pin_type=RaspberryPiHeaderPin,
    courtyard=Courtyard(5.5, 51.5),
    land_pattern=LandPattern(
        RaspberryPiHeaderPin,
        (
            Pad(
                RaspberryPiHeaderPin.BUTTON_F2_GPIO21,
                Point(1.27, -24.13),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GROUND_39,
                Point(-1.27, -24.13),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.BUTTON_F1_GPIO20,
                Point(1.27, -21.59),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.LED_EN_GPIO26,
                Point(-1.27, -21.59),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.BUTTON_OK_GPIO16,
                Point(1.27, -19.05),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.BUTTON_PASS_GPIO19,
                Point(-1.27, -19.05),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GROUND_34,
                Point(1.27, -16.51),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.BUTTON_RIGHT_GPIO13,
                Point(-1.27, -16.51),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.BUTTON_LEFT_GPIO12,
                Point(1.27, -13.97),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.BUTTON_DOWN_GPIO6,
                Point(-1.27, -13.97),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GROUND_30,
                Point(1.27, -11.43),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.BUTTON_UP_GPIO5,
                Point(-1.27, -11.43),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.ID_EEPROM_CLOCK,
                Point(1.27, -8.89),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.ID_EEPROM_DATA,
                Point(-1.27, -8.89),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.SPI_CE1_GPIO7,
                Point(1.27, -6.35),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GROUND_25,
                Point(-1.27, -6.35),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.SPI_CE0_GPIO8,
                Point(1.27, -3.81),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.SPI_CLOCK_GPIO11,
                Point(-1.27, -3.81),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GPIO25,
                Point(1.27, -1.269999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.SPI_MISO_GPIO9,
                Point(-1.27, -1.269999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GROUND_20,
                Point(1.27, 1.269999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.SPI_DATA_GPIO10,
                Point(-1.27, 1.269999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.BUTTON_F5_GPIO24,
                Point(1.27, 3.809999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.THREE_VOLTS_THREE_ALT,
                Point(-1.27, 3.809999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
                solid_zone_connection=True,
            ),
            Pad(
                RaspberryPiHeaderPin.BUTTON_F4_GPIO23,
                Point(1.27, 6.349999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.BUTTON_F3_GPIO22,
                Point(-1.27, 6.349999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GROUND_14,
                Point(1.27, 8.889999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GPIO27,
                Point(-1.27, 8.889999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GPIO18,
                Point(1.27, 11.43),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.BUTTON_RESET_GPIO17,
                Point(-1.27, 11.43),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.UART_RX_GPIO15,
                Point(1.27, 13.969999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GROUND_9,
                Point(-1.27, 13.969999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.UART_TX_GPIO14,
                Point(1.27, 16.509999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GPIO4,
                Point(-1.27, 16.509999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.GROUND_6,
                Point(1.27, 19.049999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.I2C_SCL,
                Point(-1.27, 19.049999),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.FIVE_VOLTS_ALT,
                Point(1.27, 21.59),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.I2C_SDA,
                Point(-1.27, 21.59),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.FIVE_VOLTS,
                Point(1.27, 24.13),
                1.82,
                1.82,
                shape=PadShape.CIRCLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
            ),
            Pad(
                RaspberryPiHeaderPin.THREE_VOLTS_THREE,
                Point(-1.27, 24.13),
                1.82,
                1.82,
                shape=PadShape.RECTANGLE,
                kind=PadKind.THROUGH_HOLE,
                drill_mm=1.02,
                solder_mask_margin_mm=0.05,
                solid_zone_connection=True,
            ),
        ),
        board_top_view=True,
    ),
)


class HostGpioSocket40Pin(BoardComponent[RaspberryPiHeaderPin]):
    """Place the approved PPPC202LFBN-RC with explicitly named terminals."""

    def __init__(
        self,
        registry: BoardRegistry,
        *,
        reference: str,
        placement: Placement,
        purpose: str,
        three_volts_three: Net | NoConnect,
        five_volts: Net | NoConnect,
        i2c_sda: Net | NoConnect,
        five_volts_alt: Net | NoConnect,
        i2c_scl: Net | NoConnect,
        ground_6: Net | NoConnect,
        gpio4: Net | NoConnect,
        uart_tx_gpio14: Net | NoConnect,
        ground_9: Net | NoConnect,
        uart_rx_gpio15: Net | NoConnect,
        button_reset_gpio17: Net | NoConnect,
        gpio18: Net | NoConnect,
        gpio27: Net | NoConnect,
        ground_14: Net | NoConnect,
        button_f3_gpio22: Net | NoConnect,
        button_f4_gpio23: Net | NoConnect,
        three_volts_three_alt: Net | NoConnect,
        button_f5_gpio24: Net | NoConnect,
        spi_data_gpio10: Net | NoConnect,
        ground_20: Net | NoConnect,
        spi_miso_gpio9: Net | NoConnect,
        gpio25: Net | NoConnect,
        spi_clock_gpio11: Net | NoConnect,
        spi_ce0_gpio8: Net | NoConnect,
        ground_25: Net | NoConnect,
        spi_ce1_gpio7: Net | NoConnect,
        id_eeprom_data: Net | NoConnect,
        id_eeprom_clock: Net | NoConnect,
        button_up_gpio5: Net | NoConnect,
        ground_30: Net | NoConnect,
        button_down_gpio6: Net | NoConnect,
        button_left_gpio12: Net | NoConnect,
        button_right_gpio13: Net | NoConnect,
        ground_34: Net | NoConnect,
        button_pass_gpio19: Net | NoConnect,
        button_ok_gpio16: Net | NoConnect,
        led_en_gpio26: Net | NoConnect,
        button_f1_gpio20: Net | NoConnect,
        ground_39: Net | NoConnect,
        button_f2_gpio21: Net | NoConnect,
    ) -> None:
        super().__init__(
            registry=registry,
            reference=reference,
            definition=PI_ZERO_HEADER_DEFINITION,
            placement=placement,
            purpose=purpose,
            pins={
                RaspberryPiHeaderPin.THREE_VOLTS_THREE: three_volts_three,
                RaspberryPiHeaderPin.FIVE_VOLTS: five_volts,
                RaspberryPiHeaderPin.I2C_SDA: i2c_sda,
                RaspberryPiHeaderPin.FIVE_VOLTS_ALT: five_volts_alt,
                RaspberryPiHeaderPin.I2C_SCL: i2c_scl,
                RaspberryPiHeaderPin.GROUND_6: ground_6,
                RaspberryPiHeaderPin.GPIO4: gpio4,
                RaspberryPiHeaderPin.UART_TX_GPIO14: uart_tx_gpio14,
                RaspberryPiHeaderPin.GROUND_9: ground_9,
                RaspberryPiHeaderPin.UART_RX_GPIO15: uart_rx_gpio15,
                RaspberryPiHeaderPin.BUTTON_RESET_GPIO17: button_reset_gpio17,
                RaspberryPiHeaderPin.GPIO18: gpio18,
                RaspberryPiHeaderPin.GPIO27: gpio27,
                RaspberryPiHeaderPin.GROUND_14: ground_14,
                RaspberryPiHeaderPin.BUTTON_F3_GPIO22: button_f3_gpio22,
                RaspberryPiHeaderPin.BUTTON_F4_GPIO23: button_f4_gpio23,
                RaspberryPiHeaderPin.THREE_VOLTS_THREE_ALT: three_volts_three_alt,
                RaspberryPiHeaderPin.BUTTON_F5_GPIO24: button_f5_gpio24,
                RaspberryPiHeaderPin.SPI_DATA_GPIO10: spi_data_gpio10,
                RaspberryPiHeaderPin.GROUND_20: ground_20,
                RaspberryPiHeaderPin.SPI_MISO_GPIO9: spi_miso_gpio9,
                RaspberryPiHeaderPin.GPIO25: gpio25,
                RaspberryPiHeaderPin.SPI_CLOCK_GPIO11: spi_clock_gpio11,
                RaspberryPiHeaderPin.SPI_CE0_GPIO8: spi_ce0_gpio8,
                RaspberryPiHeaderPin.GROUND_25: ground_25,
                RaspberryPiHeaderPin.SPI_CE1_GPIO7: spi_ce1_gpio7,
                RaspberryPiHeaderPin.ID_EEPROM_DATA: id_eeprom_data,
                RaspberryPiHeaderPin.ID_EEPROM_CLOCK: id_eeprom_clock,
                RaspberryPiHeaderPin.BUTTON_UP_GPIO5: button_up_gpio5,
                RaspberryPiHeaderPin.GROUND_30: ground_30,
                RaspberryPiHeaderPin.BUTTON_DOWN_GPIO6: button_down_gpio6,
                RaspberryPiHeaderPin.BUTTON_LEFT_GPIO12: button_left_gpio12,
                RaspberryPiHeaderPin.BUTTON_RIGHT_GPIO13: button_right_gpio13,
                RaspberryPiHeaderPin.GROUND_34: ground_34,
                RaspberryPiHeaderPin.BUTTON_PASS_GPIO19: button_pass_gpio19,
                RaspberryPiHeaderPin.BUTTON_OK_GPIO16: button_ok_gpio16,
                RaspberryPiHeaderPin.LED_EN_GPIO26: led_en_gpio26,
                RaspberryPiHeaderPin.BUTTON_F1_GPIO20: button_f1_gpio20,
                RaspberryPiHeaderPin.GROUND_39: ground_39,
                RaspberryPiHeaderPin.BUTTON_F2_GPIO21: button_f2_gpio21,
            },
        )
