"""Compose the complete chessboard schematic from shared blocks."""

from pathlib import Path
import sys


PROJECT_DIR = Path(__file__).parent
ELECTRONICS_ROOT = PROJECT_DIR.parents[1]
sys.path.insert(0, str(ELECTRONICS_ROOT))

from blocks.controller import add_controller  # noqa: E402
from blocks.leds import add_led_chain  # noqa: E402
from blocks.matrix import add_matrix  # noqa: E402
from blocks.power import add_power  # noqa: E402
from core import canvas  # noqa: E402


NAME = "chessboard"
SHEET_INFO = canvas.SheetInfo(
    title="Chess Smart Board - Complete Electronics",
    project="chessboard",
    comments=(
        "64 reed sensors, 64 RGB LEDs, Raspberry Pi Pico 2 W, battery power",
        "Prototype: validate current, thermals, and sensor sensitivity",
        "Generated by hardware/electronics/chessboard/generate.py; do not edit by hand",
    ),
)


def assemble() -> canvas.Schematic:
    sch = canvas.load_schematic(SHEET_INFO)
    with sch.section("Battery, protection and 5 V regulation"):
        add_power(sch)
    with sch.section("Controller, level shifting and battery telemetry"):
        add_controller(sch)
    with sch.section("8 x 8 reed-switch matrix with per-square ghosting diodes"):
        add_matrix(sch)
    with sch.section("64 x WS2812B RGB LED chain, serpentine, locally decoupled"):
        add_led_chain(sch)
    return sch


def build() -> canvas.Schematic:
    sch = assemble()
    sch.save(ELECTRONICS_ROOT, NAME)
    return sch


if __name__ == "__main__":
    build()
