#!/usr/bin/env python3
"""Give KiCad SVG layer plots a board substrate and deterministic metadata."""

from __future__ import annotations

import re
from pathlib import Path

from board import artifacts

SUBSTRATE_PATTERN = re.compile(
    r'^\s*<rect (?:id="board-substrate" )?x="0" .*?fill="#164936"/>\n',
    re.MULTILINE,
)
HEADER_MARKER = "  <desc>Image generated by PCBNEW </desc>\n"


def polish_svg(text: str, side: str) -> str:
    """Add deterministic review metadata and exactly one board substrate."""
    match = re.search(r'viewBox="([^"]+)"', text)
    if not match:
        raise ValueError("SVG has no viewBox")
    _x, _y, width, height = match.group(1).split()
    text = re.sub(
        r"<title>.*?</title>",
        f"<title>Chess board PCB — {side} copper review</title>",
        text,
        count=1,
    )
    text = SUBSTRATE_PATTERN.sub("", text)
    substrate = (
        f'  <rect id="board-substrate" x="0" y="0" width="{width}" '
        f'height="{height}" rx="2" fill="#164936"/>\n'
    )
    if HEADER_MARKER not in text:
        raise ValueError("SVG has an unexpected KiCad header")
    polished = text.replace(HEADER_MARKER, HEADER_MARKER + substrate, 1)
    return "\n".join(line.rstrip() for line in polished.splitlines()) + "\n"


def polish(path: Path, side: str) -> None:
    try:
        polished = polish_svg(path.read_text(), side)
    except ValueError as error:
        raise RuntimeError(f"{path}: {error}") from error
    path.write_text(polished)


if __name__ == "__main__":
    polish(artifacts.BOARD_TOP_SVG, "top")
    polish(artifacts.BOARD_BOTTOM_SVG, "bottom")
