"""Compose the single-square schematic from shared blocks."""

from pathlib import Path
import sys


PROJECT_DIR = Path(__file__).parent
ELECTRONICS_ROOT = PROJECT_DIR.parents[1]
sys.path.insert(0, str(ELECTRONICS_ROOT))

from blocks.square import add_column_pullup, add_led_cell, add_reed_cell  # noqa: E402
from core import canvas  # noqa: E402
from core import names as shared  # noqa: E402


NAME = "square"
SQUARE_NAME = "A1"
SHEET_INFO = canvas.SheetInfo(
    title="Chess Smart Board - Single Square",
    project="square",
    comments=(
        "Reusable per-square cell: reed, isolation diode, WS2812B, decoupling",
        "ROW/COL/+5V/GND labels match the full board; LED_DIN/LED_DOUT daisy-chain",
        "Generated by hardware/electronics/square/generate.py; do not edit by hand",
    ),
)


def assemble() -> canvas.Schematic:
    file_index, rank = shared.parse_square(SQUARE_NAME)
    name = shared.square(file_index, rank)
    sch = canvas.load_schematic(SHEET_INFO)

    col_x, sense_y = 12.0, 4.0
    with sch.section(f"Square {name} sense cell: reed, isolation diode, column pull-up"):
        add_column_pullup(
            sch,
            ref="R1",
            col_x=col_x,
            y=sense_y - 4.0,
            col_net=f"COL_{file_index}",
        )
        sch.wire(col_x - 0.9, sense_y - 4.0, col_x - 0.9, sense_y)
        add_reed_cell(
            sch,
            square_name=name,
            reed_ref="SW1",
            diode_ref="D1",
            col_x=col_x,
            y=sense_y,
            row_net=f"ROW_{rank}",
        )

    with sch.section(f"Square {name} lighting cell: WS2812B with local 100 nF"):
        add_led_cell(
            sch,
            square_name=name,
            chain_index=1,
            led_ref="U1",
            cap_ref="C1",
            x=48.0,
            y=1.0,
        )
        sch.label_pin("LED_DIN", "U1", "4")
        sch.label_pin("LED_DOUT", "U1", "2")
    return sch


def build() -> canvas.Schematic:
    sch = assemble()
    sch.save(ELECTRONICS_ROOT / "generated", NAME)
    return sch


if __name__ == "__main__":
    build()
