"""Build the component list from the schematics themselves.

Counting placed symbols rather than keeping a hand-written parts list means the
quantities cannot drift away from what the drawings actually contain.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ELECTRONICS_ROOT = Path(__file__).resolve().parents[1]
if str(ELECTRONICS_ROOT) not in sys.path:
    sys.path.insert(0, str(ELECTRONICS_ROOT))

PROJECTS = ELECTRONICS_ROOT / "projects"
OUTPUT = ELECTRONICS_ROOT / "bom.md"
GENERATED_BY = "hardware/electronics/core/bom.py"


@dataclass(frozen=True)
class Line:
    quantity: int
    value: str
    package: str
    description: str
    references: str
    ordering: str


def _sort_key(reference: str) -> tuple[str, int]:
    match = re.match(r"([A-Za-z]+)(\d+)$", reference)
    if match is None:
        return (reference, 0)
    return (match.group(1), int(match.group(2)))


def compress(references: list[str]) -> str:
    """Collapse runs of consecutive references, so 64 reeds read as SW2-SW65."""
    spans: list[str] = []
    run: list[tuple[str, int]] = []

    def flush() -> None:
        if not run:
            return
        prefix, first = run[0]
        _prefix, last = run[-1]
        if len(run) == 1:
            spans.append(f"{prefix}{first}")
        elif len(run) == 2:
            spans.append(f"{prefix}{first}, {prefix}{last}")
        else:
            spans.append(f"{prefix}{first}-{prefix}{last}")
        run.clear()

    for reference in sorted(references, key=_sort_key):
        prefix, number = _sort_key(reference)
        if run and run[-1][0] == prefix and number == run[-1][1] + 1:
            run.append((prefix, number))
            continue
        flush()
        run.append((prefix, number))
    flush()
    return ", ".join(spans)


def lines(schematic) -> list[Line]:
    """One row per distinct part, quantities counted from placed symbols."""
    grouped: dict[tuple[str, str, str, str], list[str]] = {}
    for spec in schematic.symbols:
        key = (spec.value or spec.lib, spec.package, spec.description, spec.ordering)
        grouped.setdefault(key, []).append(spec.reference)
    rows = [
        Line(len(refs), value, package, description, compress(refs), ordering)
        for (value, package, description, ordering), refs in grouped.items()
    ]
    rows.sort(key=lambda row: (-row.quantity, row.value))
    return rows


def table(rows: list[Line]) -> str:
    head = (
        "| Qty | Value | Package | Description | References |\n"
        "|----:|---|---|---|---|\n"
    )
    body = "\n".join(
        f"| {row.quantity} | {row.value} | {row.package} | {row.description} "
        f"| {row.references} |"
        for row in rows
    )
    return head + body


def purchase_table(rows: list[Line]) -> str:
    """What to order: identical parts merge however many circuits use them."""
    totals: dict[tuple[str, str], int] = {}
    for row in rows:
        key = (row.ordering or row.value, row.package)
        totals[key] = totals.get(key, 0) + row.quantity
    ordered = sorted(totals.items(), key=lambda item: (-item[1], item[0][0]))
    head = "| Qty | Part | Package |\n|----:|---|---|\n"
    body = "\n".join(
        f"| {quantity} | {part} | {package} |" for (part, package), quantity in ordered
    )
    return head + body


def projects() -> list[tuple[str, Path]]:
    """Every sheet, found the same way the runner finds them."""
    return [(path.parent.name, path) for path in sorted(PROJECTS.glob("*/generate.py"))]


def assemble(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(f"electronics_bom_{name}", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module.SHEET_INFO, module.assemble()


def document() -> str:
    chunks = [
        "# Bill of materials",
        "",
        f"Generated by `{GENERATED_BY}`; do not edit by hand. Quantities are",
        "counted from the symbols placed on each schematic, so this file and the",
        "drawings always agree.",
    ]
    for name, path in projects():
        info, schematic = assemble(name, path)
        rows = lines(schematic)
        total = sum(row.quantity for row in rows)
        chunks += [
            "",
            f"## {info.title}",
            "",
            f"`projects/{name}/generate.py` places {total} components.",
            "",
            "### By function",
            "",
            table(rows),
            "",
            "### To order",
            "",
            purchase_table(rows),
        ]
    return "\n".join(chunks) + "\n"


def main() -> None:
    OUTPUT.write_text(document())
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
