"""Compose the complete single-board schematic from shared blocks."""

from pathlib import Path
import sys


PROJECT_DIR = Path(__file__).parent
ELECTRONICS_ROOT = PROJECT_DIR.parents[1]
sys.path.insert(0, str(ELECTRONICS_ROOT))

from blocks.control_panel import add_control_panel  # noqa: E402
from blocks.host_interface import add_host_interface  # noqa: E402
from blocks.leds import add_led_chain  # noqa: E402
from blocks.power import add_power  # noqa: E402
from blocks.sensing import add_sensing  # noqa: E402
from core import canvas  # noqa: E402


NAME = "board"
SHEET_INFO = canvas.SheetInfo(
    title="Chess Smart Board - Single Board Electronics",
    project="board",
    rev="B-PROTOTYPE",
    comments=(
        "64 reed sensors, 64 SK9822 LEDs, Raspberry Pi Zero 2 W, 5 V input",
        "Two IC part numbers, both socketed; everything through-hole but the LEDs",
        "Generated by hardware/electronics/projects/board/generate.py; do not edit by hand",
    ),
)


def assemble() -> canvas.Schematic:
    sch = canvas.load_schematic(SHEET_INFO)
    with sch.section("5 V input, protection and bulk capacitance"):
        add_power(sch, origin_x=8.0, rail_y=30.0)
    with sch.section("Control panel: 12 buttons and the OLED connector"):
        add_control_panel(sch, origin_x=8.0, origin_y=-12.0)
    with sch.section("Raspberry Pi Zero 2 W socket and LED level buffer"):
        add_host_interface(sch, origin_x=110.0, origin_y=0.0)
    with sch.section("64 reed switches on four I2C expanders, one per quadrant"):
        add_sensing(sch, origin_x=200.0, origin_y=-80.0)
    with sch.section("64 x SK9822 RGB LED chain, serpentine from A1, locally decoupled"):
        add_led_chain(sch, origin_x=0.0, origin_y=-62.0)
    return sch


def build() -> canvas.Schematic:
    sch = assemble()
    sch.save(ELECTRONICS_ROOT / "generated", NAME)
    return sch


if __name__ == "__main__":
    build()
