#!/usr/bin/env python3
"""Give KiCad SVG layer plots a board substrate and deterministic metadata."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent / "generated"


def polish(path: Path, side: str) -> None:
    text = path.read_text()
    match = re.search(r'viewBox="([^"]+)"', text)
    if not match:
        raise RuntimeError(f"{path} has no SVG viewBox")
    _x, _y, width, height = match.group(1).split()
    text = re.sub(
        r"<title>.*?</title>",
        f"<title>Chess board PCB — {side} copper review</title>",
        text,
        count=1,
    )
    substrate = (
        f'<rect x="0" y="0" width="{width}" height="{height}" '
        'rx="2" fill="#164936"/>\n'
    )
    marker = "  <desc>Image generated by PCBNEW </desc>\n"
    if marker not in text:
        raise RuntimeError(f"{path} has an unexpected KiCad SVG header")
    path.write_text(text.replace(marker, marker + substrate, 1))


if __name__ == "__main__":
    polish(ROOT / "board-top.svg", "top")
    polish(ROOT / "board-bottom.svg", "bottom")
