"""Fabrication cannot bypass connectivity or KiCad's native checks."""

import json
import unittest
from pathlib import Path

from board import artifacts
from board import definition as board_definition
from components import footprints
from domain import rules
from shared.components import COMPONENTS
from tools.configure_project import render as render_project
from tools.polish_previews import polish_svg
from tools.write_bom import render as render_bom
from tools.write_bom import render_assembly_csv
from tools.write_schematic import render as render_schematic
from tools.write_schematic import render_symbol_library, row_centres

PCB = Path(__file__).resolve().parents[2]


class ReleasePolicyTest(unittest.TestCase):
    def test_svg_polishing_is_idempotent(self):
        source = (
            '<svg viewBox="0 0 320 360">\n'
            "  <title>unpolished</title>\n"
            "  <desc>Image generated by PCBNEW </desc>\n"
            "</svg>\n"
        )
        polished = polish_svg(source, "top")
        self.assertEqual(polish_svg(polished, "top"), polished)
        self.assertEqual(polished.count('id="board-substrate"'), 1)
        self.assertIn("Chess board PCB — top copper review", polished)

    def test_generated_artifact_paths_share_one_canonical_directory(self):
        paths = (
            artifacts.BOARD,
            artifacts.DSN,
            artifacts.PROJECT,
            artifacts.SCHEMATIC,
            artifacts.SYMBOL_LIBRARY,
            artifacts.SYMBOL_TABLE,
            artifacts.BOM,
            artifacts.ASSEMBLY_BOM,
            artifacts.BOARD_TOP_SVG,
            artifacts.BOARD_BOTTOM_SVG,
        )
        self.assertEqual(len(paths), len(set(paths)))
        self.assertTrue(all(path.parent == artifacts.GENERATED_DIR for path in paths))

    def test_every_single_pad_group_is_an_explicit_no_connect(self):
        design = json.loads((PCB / "board/data/netlist.json").read_text())
        for connection in design["projects"]["board"]["connections"]:
            with self.subTest(connection=connection):
                self.assertEqual(
                    connection.get("no_connect", False), len(connection["pads"]) == 1
                )

    def test_every_placed_part_resolves_to_an_approved_product(self):
        design = json.loads((PCB / "board/data/netlist.json").read_text())
        for reference, component in design["projects"]["board"]["components"].items():
            with self.subTest(reference=reference):
                spec = COMPONENTS[component["part_key"]]
                self.assertEqual(component["package"], spec.package)
                self.assertTrue(spec.manufacturer.strip())
                self.assertTrue(spec.mpn.strip())
                self.assertNotEqual(spec.manufacturer.casefold(), "generic")
                self.assertNotEqual(spec.mpn, spec.key)

    def test_schematic_rows_expand_for_tall_symbols(self):
        self.assertEqual(row_centres([]), [])
        centres = row_centres([2] * 20 + [28] + [2] * 19)
        self.assertEqual(len(centres), 2)
        self.assertGreater(centres[1] - centres[0], 40.0)

    def test_native_schematic_and_symbol_library_are_current(self):
        design = board_definition.load()
        schematic = render_schematic(design)
        self.assertIn(f'(title "{design.title}")', schematic)
        self.assertIn(f'(rev "{design.revision}")', schematic)
        self.assertEqual(artifacts.SCHEMATIC.read_text(), schematic)
        self.assertEqual(
            artifacts.SYMBOL_LIBRARY.read_text(),
            render_symbol_library(schematic),
        )

    def test_generated_boms_are_current(self):
        self.assertEqual(artifacts.BOM.read_text(), render_bom())
        self.assertEqual(
            artifacts.ASSEMBLY_BOM.read_text(),
            render_assembly_csv(),
        )

    def test_approved_bodies_fit_their_footprint_courtyards(self):
        for spec in COMPONENTS.values():
            if spec.body_mm is None or spec.package not in footprints.CATALOG:
                continue
            body = sorted(spec.body_mm[:2])
            courtyard = sorted(footprints.CATALOG[spec.package].courtyard)
            with self.subTest(part=spec.key):
                self.assertGreaterEqual(courtyard[0], body[0])
                self.assertGreaterEqual(courtyard[1], body[1])

    def test_generated_project_is_current_and_has_no_drc_exclusions(self):
        project_text = artifacts.PROJECT.read_text()
        self.assertEqual(project_text, render_project())
        project = json.loads(project_text)
        settings = project["board"]["design_settings"]
        defaults = settings["defaults"]
        constraints = settings["rules"]
        self.assertEqual(defaults["board_outline_line_width"], rules.OUTLINE_LINE_MM)
        self.assertEqual(defaults["courtyard_line_width"], rules.COURTYARD_LINE_MM)
        self.assertEqual(defaults["fab_line_width"], rules.FAB_LINE_MM)
        self.assertEqual(defaults["silk_line_width"], rules.SILK_LINE_MM)
        self.assertEqual(defaults["silk_text_size_h"], rules.SILK_TEXT_HEIGHT_MM)
        self.assertEqual(defaults["silk_text_size_v"], rules.SILK_TEXT_HEIGHT_MM)
        self.assertEqual(defaults["silk_text_thickness"], rules.SILK_LINE_MM)
        self.assertEqual(defaults["zones"]["min_clearance"], rules.POUR_CLEARANCE_MM)
        self.assertEqual(constraints["min_clearance"], rules.CLEARANCE_MM)
        self.assertEqual(
            constraints["min_copper_edge_clearance"], rules.POUR_TO_OUTLINE_MM
        )
        self.assertEqual(constraints["min_hole_clearance"], rules.HOLE_CLEARANCE_MM)
        self.assertEqual(constraints["min_hole_to_hole"], rules.HOLE_TO_HOLE_MM)
        self.assertEqual(constraints["min_track_width"], rules.TRACE_WIDTH_MM)
        self.assertEqual(constraints["min_via_diameter"], rules.VIA_PAD_MM)
        self.assertEqual(settings.get("drc_exclusions", []), [])
        self.assertNotIn("ignore", settings["rule_severities"].values())

    def test_completed_routing_subsystems_stay_complete(self):
        drc = json.loads((PCB / "generated/drc.json").read_text())
        self.assertEqual(drc["violations"], [])
        self.assertEqual(drc["unconnected_items"], [])
        self.assertEqual(drc["schematic_parity"], [])

    def test_native_erc_is_clean(self):
        erc = json.loads((PCB / "generated/erc.json").read_text())
        violations = [
            violation
            for sheet in erc.get("sheets", [])
            for violation in sheet.get("violations", [])
        ]
        self.assertEqual(violations, [])

    def test_pcb_capabilities_are_owned_by_the_package(self):
        justfile = (PCB / "justfile").read_text()
        for capability in (
            "quality",
            "generate",
            "pins-check",
            "erc",
            "drc",
            "test",
            "previews",
            "review",
            "fabrication",
            "release",
            "check-fast",
        ):
            with self.subTest(capability=capability):
                self.assertIn(f"{capability}:", justfile)
        self.assertIn("review: quality previews", justfile)
        self.assertIn("release: quality previews fabrication", justfile)

    def test_release_capability_enforces_the_gate_before_gerbers(self):
        justfile = (PCB / "justfile").read_text()
        gate = justfile.index("PCB_RELEASE=1")
        fabrication = justfile.index("pcb export gerbers")
        self.assertLess(gate, fabrication)
        self.assertIn("fabrication: release-test", justfile)
        self.assertIn("python3 -m unittest discover", justfile)
        self.assertIn("--severity-exclusions", justfile)
        workflows = PCB.parents[1] / ".github/workflows"
        hardware = (workflows / "hardware.yml").read_text()
        self.assertIn("just --justfile hardware/pcb/justfile review", hardware)
        for orchestrator in ("ci.yml", "pr.yml"):
            with self.subTest(orchestrator=orchestrator):
                self.assertIn(
                    "uses: ./.github/workflows/hardware.yml",
                    (workflows / orchestrator).read_text(),
                )


if __name__ == "__main__":
    unittest.main()
