[package]
name = "chess"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
autotests = false
autobenches = false

[dependencies]
chess-core = { path = "../core" }
embedded-chess-engine = { package = "chess-engine", version = "0.1.2", default-features = false }
logger = { path = "../logger" }
sha2 = { version = "0.11.0", default-features = false }

[[test]]
name = "model"
path = "tests/model/main.rs"

[[test]]
name = "rules"
path = "tests/rules/main.rs"

[[test]]
name = "game"
path = "tests/game/main.rs"

[[test]]
name = "history"
path = "tests/history/main.rs"

[[test]]
name = "player"
path = "tests/player/main.rs"

[[test]]
name = "session"
path = "tests/session/main.rs"

[[test]]
name = "perft"
path = "tests/perft/main.rs"

[[test]]
name = "logging"
path = "tests/logging/main.rs"

[[bench]]
name = "perft"
path = "benches/performance/perft.rs"
harness = false
