//! Typed field descriptors generated by [`persistence_schema!`](crate::persistence_schema).

mod error;
mod field;
mod validation;

pub use error::{RetrieveError, SaveError};
pub use field::Field;
#[doc(hidden)]
pub use validation::validate_keys;
