"""Generate the board's fabrication artwork, and say what is still missing.

Writes the layer stack, a rendered preview of both sides, and a routing report.
The manufacturing package is only written when the report says every design contract
connection is realised in copper, because valid Gerber files and a working board
are not the same thing and a fab cannot tell the difference.
"""

from pathlib import Path
import sys


PROJECT_DIR = Path(__file__).parent
PCB_ROOT = PROJECT_DIR.parents[1]
sys.path.insert(0, str(PCB_ROOT))
GENERATED = PCB_ROOT / "generated"
GENERATED.mkdir(parents=True, exist_ok=True)

from core import connectivity, layers, nets, placement, routing, rules  # noqa: E402

NAME = "board"
STACK_DIRECTORY = GENERATED / "gerber"
PACKAGE_PATH = GENERATED / f"{NAME}-pcbway.zip"
REPORT_PATH = GENERATED / "routing.md"
PREVIEW_PATHS = {
    "top": GENERATED / f"{NAME}-top.svg",
    "bottom": GENERATED / f"{NAME}-bottom.svg",
}


def assemble():
    """Placements, artwork and the layer stack, with nothing written."""
    placements = placement.build()
    artwork, counts = routing.build_artwork(placements)
    pad_net = nets.pad_nets()
    stack = layers.build_stack(placements, artwork, pad_net)
    statuses = connectivity.analyse(placements, artwork)
    return placements, artwork, stack, statuses, counts


def write_report(statuses, counts, placements) -> dict:
    summary = connectivity.summary(statuses)
    body = [
        "# Routing status",
        "",
        "Generated by `hardware/pcb/projects/board/generate.py`; do not edit by",
        "hand. This file is the honest state of the layout: Gerber output is",
        "valid long before a board would work, so the manufacturing package is",
        "withheld until every connection below is routed.",
        "",
        "## Board",
        "",
        f"- {len(placements)} parts placed",
        f"- {counts['traces']} trace segments, {counts['vias']} vias",
        f"- {counts['led_chain_links']} LED chain links routed",
        f"- {counts['ground_stitches']} surface-mount ground pads stitched to the pour",
        f"- {counts['silk_segments']} silkscreen segments",
        f"- {rules.TRACE_WIDTH_MM:g} mm signal traces, "
        f"{rules.CLEARANCE_MM:g} mm clearance",
        "",
        "## Connectivity",
        "",
        "```",
        connectivity.report(statuses),
        "```",
        "",
    ]
    if summary["complete"]:
        body += [
            "Every connection is routed, so "
            f"`{PACKAGE_PATH.name}` has been written and is ready to upload.",
            "",
            "Check it against the fab's own preview before ordering. This "
            "toolchain verifies that nets are joined, not that copper is clear "
            "of copper: it has no design-rule check over finished geometry.",
        ]
    else:
        body += [
            f"`{PACKAGE_PATH.name}` has **not** been written, because "
            f"{summary['unrouted']} connections are still open.",
            "",
            "The outstanding work is the reed sense lines, the buses and 5 V "
            "distribution. Those all compete for the same top-layer space and "
            "need a router that reasons about obstacles, which this stage does "
            "not have.",
        ]
    REPORT_PATH.write_text("\n".join(body) + "\n")
    print(f"wrote {REPORT_PATH}")
    return summary


def write_previews(stack) -> None:
    for side, path in PREVIEW_PATHS.items():
        path.write_text(str(stack.to_pretty_svg(side=side)))
        print(f"wrote {path}")


def build() -> dict:
    placements, _artwork, stack, statuses, counts = assemble()

    if STACK_DIRECTORY.exists():
        for stale in STACK_DIRECTORY.iterdir():
            stale.unlink()
    stack.save_to_directory(STACK_DIRECTORY)
    print(f"wrote {STACK_DIRECTORY}")

    write_previews(stack)
    summary = write_report(statuses, counts, placements)

    PACKAGE_PATH.unlink(missing_ok=True)
    if summary["complete"]:
        stack.save_to_zipfile(PACKAGE_PATH)
        print(f"wrote {PACKAGE_PATH}")
    else:
        print(
            f"withheld {PACKAGE_PATH.name}: "
            f"{summary['unrouted']} connections are unrouted"
        )
    return summary


if __name__ == "__main__":
    build()
