[package]
name = "firmware"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
logger = { path = "../../crates/logger", features = ["std"] }
menu = { path = "../../crates/menu" }
tokio = { version = "1.53.1", features = ["rt", "sync", "time"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt", "sync", "test-util", "time"] }
