[package]
name = "firmware"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
display-interface = "0.5.0"
embedded-graphics = "0.8.2"
embedded-hal = "1.0.0"
logger = { path = "../../crates/logger", features = ["std"] }
menu = { path = "../../crates/menu" }
ssd1306 = "0.10.0"
tokio = { version = "1.53.1", features = ["rt", "sync", "time"] }

[dev-dependencies]
embedded-graphics-simulator = { version = "0.8.0", default-features = false }
tokio = { version = "1.53.1", features = ["macros", "rt", "sync", "test-util", "time"] }
