"""Typed surface used by the STEP adapter (CadQuery 2.6.1)."""

class Color:
    def __init__(self, r: float, g: float, b: float) -> None: ...

class Workplane:
    def __init__(self, plane: str = "XY") -> None: ...
    def box(self, length: float, width: float, height: float) -> Workplane: ...
    def cylinder(self, height: float, radius: float) -> Workplane: ...
    def translate(self, vector: tuple[float, float, float]) -> Workplane: ...

class Assembly:
    def __init__(self, name: str = "") -> None: ...
    def add(self, obj: Workplane, name: str, color: Color) -> Assembly: ...
    def export(self, path: str) -> Assembly: ...
