"""Typed subset of KiCad 9's SWIG API used by the PCB source.

SWIG's generated Python signatures omit return types and give the scalar unit
converters misleading tuple unions. Keep this boundary explicit; add signatures
when source starts using another native operation, never a catch-all Any.
"""

from collections.abc import Iterable, Mapping
from typing import overload

F_Cu: int
B_Cu: int
In1_Cu: int
In2_Cu: int
In3_Cu: int
In4_Cu: int
In5_Cu: int
In6_Cu: int
F_CrtYd: int
F_Fab: int
F_SilkS: int
Edge_Cuts: int
PAD_ATTRIB_NPTH: int
PAD_ATTRIB_PTH: int
PAD_ATTRIB_SMD: int
PAD_DRILL_SHAPE_OBLONG: int
PAD_SHAPE_CIRCLE: int
PAD_SHAPE_OVAL: int
PAD_SHAPE_RECT: int
SHAPE_T_SEGMENT: int

class VECTOR2I:
    x: int
    y: int
    @overload
    def __init__(self, x: int, y: int) -> None: ...
    @overload
    def __init__(self, other: VECTOR2I) -> None: ...

# Only scalar conversions are used by the board generator.
def FromMM(value: float) -> int: ...
def ToMM(value: float) -> float: ...

class BOX2I:
    def GetLeft(self) -> int: ...
    def GetRight(self) -> int: ...
    def GetTop(self) -> int: ...
    def GetBottom(self) -> int: ...

class LSET:
    def CuStack(self) -> Iterable[int]: ...

class BOARD_DESIGN_SETTINGS:
    m_MinClearance: int
    m_TrackMinWidth: int
    m_HoleClearance: int
    m_HoleToHoleMin: int
    m_CopperEdgeClearance: int
    m_ViasMinSize: int
    m_ViasMinAnnularWidth: int
    m_MinThroughDrill: int
    m_SilkClearance: int
    m_SolderMaskMinWidth: int
    def SetBoardThickness(self, thickness: int) -> None: ...

class BOARD:
    def GetTitleBlock(self) -> TITLE_BLOCK: ...
    def SetTitleBlock(self, block: TITLE_BLOCK) -> None: ...
    def GetNetCount(self) -> int: ...
    def FindNet(self, name: str) -> NETINFO_ITEM | None: ...
    def GetNetsByName(self) -> Mapping[object, NETINFO_ITEM]: ...
    def __init__(self) -> None: ...
    def Add(self, item: BOARD_ITEM | NETINFO_ITEM) -> None: ...
    def Remove(self, item: BOARD_ITEM) -> None: ...
    def GetFootprints(self) -> Iterable[FOOTPRINT]: ...
    def GetDrawings(self) -> Iterable[BOARD_ITEM]: ...
    def GetTracks(self) -> Iterable[PCB_TRACK]: ...
    def GetBoardEdgesBoundingBox(self) -> BOX2I: ...
    def GetDesignSettings(self) -> BOARD_DESIGN_SETTINGS: ...
    def SetCopperLayerCount(self, count: int) -> None: ...
    def FindFootprintByReference(self, reference: str) -> FOOTPRINT | None: ...
    def Zones(self) -> Iterable[ZONE]: ...

class BOARD_ITEM:
    m_Uuid: KIID
    def GetPosition(self) -> VECTOR2I: ...
    def SetPosition(self, position: VECTOR2I) -> None: ...
    def GetBoundingBox(self) -> BOX2I: ...
    def GetLayer(self) -> int: ...
    def SetLayer(self, layer: int) -> None: ...
    def IsOnLayer(self, layer: int) -> bool: ...

class NETINFO_ITEM:
    def __init__(self, board: BOARD, name: str, code: int) -> None: ...
    def GetNetCode(self) -> int: ...
    def GetNetname(self) -> str: ...

class BOARD_CONNECTED_ITEM(BOARD_ITEM):
    def GetNetCode(self) -> int: ...
    def GetNetname(self) -> str: ...
    def SetNet(self, net: NETINFO_ITEM) -> None: ...
    def GetNet(self) -> NETINFO_ITEM: ...
    def GetLayerSet(self) -> LSET: ...
    def SetLayerSet(self, layers: LSET) -> None: ...

class FOOTPRINT(BOARD_ITEM):
    def __init__(self, board: BOARD | FOOTPRINT | None) -> None: ...
    def Duplicate(self) -> FOOTPRINT: ...
    def GetFieldText(self, name: str) -> str: ...
    def GetFieldsText(self) -> dict[str, str]: ...
    def SetField(self, name: str, text: str) -> None: ...
    def HasFieldByName(self, name: str) -> bool: ...
    def GetOrientationDegrees(self) -> float: ...
    def Add(self, item: BOARD_ITEM) -> None: ...
    def Pads(self) -> Iterable[PAD]: ...
    def GraphicalItems(self) -> Iterable[PCB_SHAPE]: ...
    def GetFields(self) -> Iterable[PCB_FIELD]: ...
    def SetPath(self, path: KIID_PATH) -> None: ...
    def GetReference(self) -> str: ...
    def SetReference(self, reference: str) -> None: ...
    def GetValue(self) -> str: ...
    def SetValue(self, value: str) -> None: ...
    def SetLibDescription(self, description: str) -> None: ...
    def SetOrientationDegrees(self, degrees: float) -> None: ...
    def Reference(self) -> PCB_TEXT: ...
    def Value(self) -> PCB_TEXT: ...
    def SetBoardOnly(self, enabled: bool) -> None: ...
    def SetExcludedFromBOM(self, excluded: bool) -> None: ...
    def SetExcludedFromPosFiles(self, excluded: bool) -> None: ...

class PAD(BOARD_CONNECTED_ITEM):
    def __init__(self, parent: FOOTPRINT | PAD | None) -> None: ...
    def SetOrientationDegrees(self, degrees: float) -> None: ...
    def GetParent(self) -> FOOTPRINT: ...
    def GetParentFootprint(self) -> FOOTPRINT: ...
    def GetNumber(self) -> str: ...
    def SetNumber(self, number: str) -> None: ...
    def GetAttribute(self) -> int: ...
    def SetAttribute(self, attribute: int) -> None: ...
    def GetShape(self) -> int: ...
    def SetShape(self, shape: int) -> None: ...
    def GetSize(self) -> VECTOR2I: ...
    def SetSize(self, size: VECTOR2I) -> None: ...
    def SetDrillSize(self, size: VECTOR2I) -> None: ...
    def GetDrillSize(self) -> VECTOR2I: ...
    def SetDrillShape(self, shape: int) -> None: ...
    def SetLocalSolderMaskMargin(self, margin: int) -> None: ...
    def PTHMask(self) -> LSET: ...
    def SMDMask(self) -> LSET: ...
    def UnplatedHoleMask(self) -> LSET: ...

class PCB_TRACK(BOARD_CONNECTED_ITEM):
    def __init__(self, board: BOARD) -> None: ...
    def GetStart(self) -> VECTOR2I: ...
    def GetEnd(self) -> VECTOR2I: ...
    def SetStart(self, start: VECTOR2I) -> None: ...
    def SetEnd(self, end: VECTOR2I) -> None: ...
    def GetWidth(self, layer: int = ...) -> int: ...
    def SetWidth(self, width: int, layer: int = ...) -> None: ...

class PCB_VIA(PCB_TRACK):
    def SetDrill(self, drill: int) -> None: ...
    def GetDrillValue(self) -> int: ...

class PCB_SHAPE(BOARD_ITEM):
    def GetStart(self) -> VECTOR2I: ...
    def GetEnd(self) -> VECTOR2I: ...
    def GetShape(self) -> int: ...
    def GetWidth(self) -> int: ...
    def __init__(self, parent: BOARD | FOOTPRINT) -> None: ...
    def SetShape(self, shape: int) -> None: ...
    def SetStart(self, start: VECTOR2I) -> None: ...
    def SetEnd(self, end: VECTOR2I) -> None: ...
    def SetWidth(self, width: int) -> None: ...

class PCB_TEXT(BOARD_ITEM):
    def GetText(self) -> str: ...
    def __init__(self, board: BOARD) -> None: ...
    def SetText(self, text: str) -> None: ...
    def SetTextSize(self, size: VECTOR2I) -> None: ...
    def SetTextThickness(self, thickness: int) -> None: ...
    def SetVisible(self, visible: bool) -> None: ...

class SHAPE_POLY_SET:
    def NewOutline(self) -> int: ...
    def Append(self, x: int, y: int) -> None: ...

class ZONE(BOARD_CONNECTED_ITEM):
    def __init__(self, board: BOARD) -> None: ...
    def Outline(self) -> SHAPE_POLY_SET: ...

class ZONE_FILLER:
    def __init__(self, board: BOARD) -> None: ...
    def Fill(self, zones: Iterable[ZONE]) -> None: ...

class PCB_FIELD(PCB_TEXT):
    def GetName(self) -> str: ...

class KIID_PATH:
    def __init__(self, path: str) -> None: ...

class KIID:
    def AsString(self) -> str: ...
    @staticmethod
    def SeedGenerator(seed: int) -> None: ...

def SaveBoard(path: str, board: BOARD) -> bool: ...
def LoadBoard(path: str) -> BOARD: ...
def ExportSpecctraDSN(board: BOARD, path: str) -> bool: ...
def GetBuildVersion() -> str: ...

class TITLE_BLOCK:
    def GetTitle(self) -> str: ...
    def SetTitle(self, text: str) -> None: ...
    def GetRevision(self) -> str: ...
    def SetRevision(self, text: str) -> None: ...
